/*************************************************
 File: CustomerList.java
 By: Jeanine Nebrija
 Date: 5/20/24
 Compile: Open directory as IntelliJ project, compile and run.
 System: Windows w/ Java
 Description: Initializing to select button of a customer's list
 *************************************************/

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment6View;

import Assignment6Model.BankCustomer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author karunmehta
 */
public class CustomerList extends JFrame {
    List<BankCustomer> customers;

    /**
     * Creates new form CustomerList
     */
    public CustomerList(List<BankCustomer> data) {
        initComponents();
        this.setVisible(true);

        customers=data;
        reloadList();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void reloadList(){
        String[] labels = new String[customers.size()];
        int i=0;
        for(BankCustomer c : customers){
            labels[i]=c.getName();
            i++;
        }

        custList.setModel(new AbstractListModel<String>() {
            public int getSize() { return labels.length; }
            public String getElementAt(int i) { return labels[i]; }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsButton = new JButton();
        cancelButton = new JButton();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        custList = new JList<>();
        jLabel5 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(new Dimension(10, 5));

        detailsButton.setText("Show Details");
        detailsButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                dispose();
            }
        });

        jLabel1.setText("Customer List:");

        custList.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(custList);

        jLabel5.setFont(new Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("List of Customers");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(detailsButton)
                        .addGap(68, 68, 68)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 372, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsButton)
                    .addComponent(cancelButton))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        showCustomerDetail();
    }//GEN-LAST:event_detailsActionPerformed


    private void showCustomerDetail(){
        if(custList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Please select a Customer.");
            return;
        }
        new CustomerDetail(customers.get(custList.getSelectedIndex()),this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JList<String> custList;
    private JButton detailsButton;
    private JLabel jLabel1;
    private JLabel jLabel5;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
